package com.example.bem.validation;

/**
 * Machine-readable error codes returned in HTTP error bodies.
 */
public enum ErrorCode {

    INVALID_JSON("INVALID_JSON"),
    TIP_SPEED_RATIO_NOT_POSITIVE("TIP_SPEED_RATIO_NOT_POSITIVE"),
    NOT_ENOUGH_STATIONS("NOT_ENOUGH_STATIONS"),
    AIRFOIL_TABLE_EMPTY("AIRFOIL_TABLE_EMPTY"),
    RADIUS_NOT_MONOTONIC("RADIUS_NOT_MONOTONIC"),
    BLADES_NOT_POSITIVE_INTEGER("BLADES_NOT_POSITIVE_INTEGER"),
    AIRFOIL_NAME_MISSING("AIRFOIL_NAME_MISSING"),
    AIRFOIL_NOT_FOUND("AIRFOIL_NOT_FOUND"),
    AIRFOIL_ALREADY_EXISTS("AIRFOIL_ALREADY_EXISTS"),
    RADIUS_OUT_OF_RANGE("RADIUS_OUT_OF_RANGE"),
    CHORD_NOT_POSITIVE("CHORD_NOT_POSITIVE"),
    POLAR_NOT_ORDERED("POLAR_NOT_ORDERED"),
    POLAR_POINT_INVALID("POLAR_POINT_INVALID"),
    ROTOR_PARAMETER_INVALID("ROTOR_PARAMETER_INVALID"),
    STATION_NOT_FOUND("STATION_NOT_FOUND"),
    ITERATION_NOT_CONVERGED("ITERATION_NOT_CONVERGED"),
    INTERNAL_ERROR("INTERNAL_ERROR");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }

    public String code() {
        return code;
    }
}
